image: "redoxos/redoxer"

variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
format:
  cache:
    paths:
      - cargo/
      - target/
  script:
    - rustup default nightly
    - rustup component add rustfmt
    - cargo +nightly fmt --all -- --check

linux:
  image: 'rust:1.36.0'
  cache:
    paths:
      - cargo/
      - target/
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq capnproto libcapnp-dev
  script:
    - cargo check
    - cd members/shellac-json && cargo check

linux:stable:
  cache:
    paths:
      - cargo/
      - target/
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq capnproto libcapnp-dev
  script:
    - cargo check
    - cd members/shellac-json && cargo build && cd ../..
    # Simple integration test
    - ./members/shellac-json/target/debug/shellac-json encode '{"word":4,"argv":["git","-f","-f","-p","-"]}' | cargo run | ./members/shellac-json/target/debug/shellac-json decode > tests/result 2> /dev/null
    - diff tests/result tests/expected

redox:
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq capnproto libcapnp-dev build-essential curl git
    - cargo clean
  script:
    - redoxer check
    - cd members/shellac-json && redoxer check
